server:
  port: ${PORT:31001}
spring:
  application:
    name: nm-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://localhost:27017/nm_cms
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtualHost: /
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50101/eureka/}
  instance:
   prefer‐ip‐address: true
   ip‐address: ${IP_ADDRESS:127.0.0.1}
   instance‐id: ${spring.application.name}:${server.port} #指定实例id
