server:
  port: ${PORT:50101}
spring:
  application:
    name: nm-govern-center
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://eureka02:50102/eureka/}
  server:
    enable-self-preservation: false   #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000
  instance:
     hostname: ${EUREKA_DOMAIN:eureka01}